baseURL = "https://idiosapps.github.io"
languageCode = "en-gb"
title = "James' Digital Garden"
theme = "digital-garden"
themesdir = "./themes"
copyright = "James Clark Â©"
rssLimit = 5


[params]
  name = "James Clark"
  description = "ğŸŒ± ğŸŒ¿ ğŸŒ³ & my digital garden ğŸ¤¯ ğŸ“– âœï¸ "
  initials = "JC"
  googleAnalytics = ""


  [[params.social]]
    name = "RSS"
    link = "https://raw.githubusercontent.com/IdiosApps/IdiosApps.github.io/gh-pages/index.xml"
    icon = "fas fa-rss"

  [[params.social]]
    name = "Github"
    link = "https://github.com/IdiosApps"
    icon = "fab fa-github"

  [[params.social]]
    name = "Medium" 
    link = "https://medium.com/@james.sw.clark"
    icon = "fab fa-medium-m"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/james-sw-clark/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
#  [[menu.main]]
#    name = "Projects"
#    url = "/projects/"
#    weight = 2
#  [[menu.main]]
#    name = "Library"
#    url = "/library/"
#    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'